# Yelp Reviews Sentiment Prediction
https://www.kaggle.com/datasets/marklvl/sentiment-labelled-sentences-data-set

In [2]:
import numpy as np
import pandas as pd

In [3]:
with open('yelp.txt', 'r') as file:
    lines = file.read()
lines

'Wow... Loved this place.\t1\nCrust is not good.\t0\nNot tasty and the texture was just nasty.\t0\nStopped by during the late May bank holiday off Rick Steve recommendation and loved it.\t1\nThe selection on the menu was great and so were the prices.\t1\nNow I am getting angry and I want my damn pho.\t0\nHoneslty it didn\'t taste THAT fresh.)\t0\nThe potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.\t0\nThe fries were great too.\t1\nA great touch.\t1\nService was very prompt.\t1\nWould not go back.\t0\nThe cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced.\t0\nI tried the Cape Cod ravoli, chicken,with cranberry...mmmm!\t1\nI was disgusted because I was pretty sure that was human hair.\t0\nI was shocked because no signs indicate cash only.\t0\nHighly recommended.\t1\nWaitress was a little slow in service.\t0\nThis place is not worth your time, let alone Vegas.\t0\ndid not like at all.\

In [4]:
lines = lines.split('\n')
lines

['Wow... Loved this place.\t1',
 'Crust is not good.\t0',
 'Not tasty and the texture was just nasty.\t0',
 'Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.\t1',
 'The selection on the menu was great and so were the prices.\t1',
 'Now I am getting angry and I want my damn pho.\t0',
 "Honeslty it didn't taste THAT fresh.)\t0",
 'The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.\t0',
 'The fries were great too.\t1',
 'A great touch.\t1',
 'Service was very prompt.\t1',
 'Would not go back.\t0',
 'The cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced.\t0',
 'I tried the Cape Cod ravoli, chicken,with cranberry...mmmm!\t1',
 'I was disgusted because I was pretty sure that was human hair.\t0',
 'I was shocked because no signs indicate cash only.\t0',
 'Highly recommended.\t1',
 'Waitress was a little slow in service.\t0',
 'This place is not worth

In [5]:
X_data = []
y_data = []
for i in range(len(lines)):
    if lines[i]:
        X_data.append(lines[i][:-3])
        y_data.append(int(lines[i][-1]))
    else:
        continue
    
y_data

[1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,


In [6]:
# Use try except to avoid error due to this unwanted entry
lines[1000]

''

In [7]:
X_data = np.array(X_data)
y_data = np.array(y_data)

In [8]:
X_data.shape, y_data.shape

((1000,), (1000,))

In [9]:
df = pd.DataFrame({
    'X': X_data,
    'y': y_data
})

In [10]:
df

X  y
0                              Wow... Loved this place  1
1                                    Crust is not good  0
2             Not tasty and the texture was just nasty  0
3    Stopped by during the late May bank holiday of...  1
4    The selection on the menu was great and so wer...  1
..                                                 ... ..
995  I think food should have flavor and texture an...  0
996                            Appetite instantly gone  0
997  Overall I was not impressed and would not go back  0
998  The whole experience was underwhelming, and I ...  0
999  Then, as if I hadn't wasted enough of my life ...  0

[1000 rows x 2 columns]

In [11]:
df.y.nunique()

2

In [12]:
df.y.value_counts()

1    500
0    500
Name: y, dtype: int64

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_count = v.fit_transform(X_data)
X_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import BernoulliNB, MultinomialNB

from sklearn.model_selection import GridSearchCV

In [24]:
model_params = {
    'logistic_regression': {
        'model': LogisticRegression(max_iter=10000, random_state=3),
        'params': {
            'C': [1, 2, 4, 8, 16, 32]
        }
    },
    'decision_tree': {
        'model': DecisionTreeClassifier(random_state=3),
        'params': {
            'criterion': ['gini', 'entropy']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(random_state=3),
        'params': {
            'n_estimators': [100, 200, 300, 400],
            'criterion': ['gini', 'entropy', 'log_loss']
        }
    },
    'svm': {
        'model': SVC(gamma='auto', random_state=3),
        'params': {
            'C': [1, 2, 4, 8, 16, 32],
            'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
        }
    },
    'bernoulli_nb': {
        'model': BernoulliNB(),
        'params': {
            'alpha': [0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000]
        }
    },
    'multinomial_nb': {
        'model': MultinomialNB(),
        'params': {
            'alpha': [0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000]
        }
    }
}

In [25]:
scores = []

for name, models in model_params.items():
    clf = GridSearchCV(models['model'], models['params'], cv=5, return_train_score=False)
    clf.fit(X_count, y_data)
    scores.append({
        'model': name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    print(name + ' 100%')

scores_df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
scores_df

logistic_regression 100%
decision_tree 100%
random_forest 100%
svm 100%
bernoulli_nb 100%
multinomial_nb 100%


model  best_score  \
0  logistic_regression       0.805   
1        decision_tree       0.723   
2        random_forest       0.808   
3                  svm       0.797   
4         bernoulli_nb       0.774   
5       multinomial_nb       0.784   

                                     best_params  
0                                       {'C': 8}  
1                          {'criterion': 'gini'}  
2  {'criterion': 'entropy', 'n_estimators': 200}  
3                   {'C': 1, 'kernel': 'linear'}  
4                                 {'alpha': 0.1}  
5                                   {'alpha': 1}

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_count, y_data, test_size=0.3)

model = RandomForestClassifier(criterion='entropy', n_estimators=200)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.7966666666666666

In [34]:
sentence = ['food is not good']

sentence_count = v.transform(sentence)
sentence_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
model.predict(sentence_count)

array([0])

In [44]:
import joblib as jl
jl.dump(model, 'model')

['model']